name: humble

on: [push, pull_request]

jobs:
    job1:
        name: Build
        runs-on: ubuntu-22.04
        steps:
            - name: Install ROS2 Humble 
              run: |
                  # Ref: https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html
                  sudo apt update && sudo apt install locales
                  sudo locale-gen en_US en_US.UTF-8
                  sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
                  export LANG=en_US.UTF-8
                  sudo apt install software-properties-common
                  sudo add-apt-repository universe
                  sudo apt update && sudo apt install curl
                  sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
                  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
                  sudo apt update
                  sudo apt upgrade
                  sudo apt install ros-humble-desktop
                  sudo apt install ros-humble-twist-mux
                  source /opt/ros/humble/setup.bash
            - name: Create Workspace
              run: |
                  mkdir -p ~/ros2_ws/src
            - name: Install Dependencies and Build Botanbot Packges
              run: |
                  source /opt/ros/humble/setup.bash
                  sudo apt install python3-colcon-common-extensions
                  sudo apt install -y python3-rosdep2
                  sudo apt-get install git
                  rosdep update
                  cd ~/ros2_ws/src
                  git clone --recursive https://github.com/NMBURobotics/botanbot_sim.git
                  cd ~/ros2_ws
                  rosdep install -y -r -q --from-paths src --ignore-src --rosdistro humble   
                  colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --parallel-workers 4
